apiVersion: 1

datasources:
  - name: Sentinel PostgreSQL
    type: postgres
    access: proxy
    url: sentinel-db:5432
    user: sentinel_user
    database: sentinel
    secureJsonData:
      password: sentinel_password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
      database: sentinel
    isDefault: true