apiVersion: 1

datasources:
  - name: Sentinel PostgreSQL
    type: postgres
    uid: postgresql
    url: sentinel-db:5432
    database: sentinel
    user: sentinel_user
    secureJsonData:
      password: sentinel_password
    jsonData:
      sslmode: disable
