apiVersion: 1
groups:
    - orgId: 1
      name: multiservice_attackers
      folder: attack paterns
      interval: 10m
      rules:
        - uid: dfep1q3yg3n5sf
          title: Attack Pattern Detection
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: dfeotjrrru2o0b
              model:
                dataset: sentinel
                editorMode: code
                format: table
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: "SELECT COUNT(DISTINCT source_ip) as multi_service_attackers\nFROM events\nWHERE \n  timestamp > NOW() - INTERVAL '10 minutes'\nGROUP BY source_ip\nHAVING COUNT(DISTINCT sensor_type) > 2"
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10m
          annotations: {}
          labels:
            alert_type: coordinated_attack
            team: security
          isPaused: false
          notification_settings:
            receiver: Honeypot Alerts
